
- hosts: windows
  tasks:
  - name: copy source file to HFR server
    win_copy: src=package/{{filename}} dest=E:\Adminutils\LCM_Jenkins
  - name: copy import script to HFR server
    win_copy: src=package/LCM_Import_TEST.bat dest=E:\Adminutils\LCM_Jenkins force=yes
  - name: Import
    win_shell: Start-Process powershell -Verb runAs;.\LCM_Export_TEST.bat
    args:
       chdir: E:\Adminutils\LCM_Jenkins
    register: Importdata
  - name: show result
    debug: 
      msg: "{{Importdata.stdout_lines}}"
